# Generated by Django 4.2.16 on 2024-10-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='img',
        ),
        migrations.AddField(
            model_name='customuser',
            name='prifile_picture',
            field=models.ImageField(default='media/defaults.jpeg', upload_to='media/'),
        ),
    ]
