# Generated by Django 4.2.16 on 2024-10-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_img_customuser_prifile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='prifile_picture',
            new_name='profile_picture',
        ),
    ]
