# Generated by Django 5.1.2 on 2024-10-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_auth_2fa_customuser_mfa_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_2fa',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
