# Generated by Django 5.1.2 on 2024-10-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_auth_2fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mfa_secret',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
