# Generated by Django 4.2.16 on 2024-10-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_request_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
