# Generated by Django 4.2.16 on 2024-10-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user1',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='user2',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
